# syntax=docker.io/docker/dockerfile:1

# Base image
FROM node:18-alpine AS base

# Dependencies Layer
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
RUN npm install sharp

# Build Layer
FROM base AS builder
WORKDIR /app

# Reuse node_modules from deps layer
COPY --from=deps /app/node_modules ./node_modules

# Copy all project files
COPY . .

# Build the Next.js app in standalone mode
RUN npm run build

# Production Layer
FROM base AS runner
WORKDIR /app

# Create a safer non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only the necessary build artifacts
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js", "-H", "0.0.0.0"]
