version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    ports:
      - "4000:4000"
    restart: always
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
